openapi: 3.0.0
info:
  title: Threat Hunt REST API
  description: Simple REST API for threat hunting data
  version: "0.1"

servers:
  - url: "/api"

paths:
  /tenants:
    get:
      summary: Returns a list of tenants.
      operationId: tenants.index
      responses:
        "200":
          description: A JSON array of tenant objects
