openapi: 3.0.0
info:
  title: Threat Hunt REST API
  description: Simple REST API for threat hunting data
  version: "0.1"

servers:
  - url: "/api"

components:
  schemas:
    Tenant:
      type: "object"
      required:
        - name
      properties:
        name:
          type: string

paths:
  /tenants:
    get:
      summary: Returns a list of tenants.
      operationId: tenants.index
      responses:
        "200":
          description: A JSON array of tenant objects
    post:
      summary: Create a tenant.
      operationId: tenants.create
      requestBody:
        description: Tenant to create
        required: True
        content:
          application/json:
            schema:
              x-body-name: tenant
              $ref: "#/components/schemas/Tenant"
      responses:
        "201":
          description: Created tenant
