openapi: 3.0.0
info:
  title: Threat Hunt REST API
  description: Simple REST API for threat hunting data
  version: "0.1"

servers:
  - url: "/api"

components:
  schemas:
    Tenant:
      type: "object"
      required:
        - name
      properties:
        name:
          type: string
  parameters:
    id:
      name: id
      description: ID of tenant to retrieve
      in: path
      required: True
      schema:
        type: string

paths:
  /tenants:
    get:
      summary: Returns a list of tenants.
      operationId: tenants.index
      responses:
        "200":
          description: A JSON array of tenant objects
    post:
      summary: Creates a tenant.
      operationId: tenants.create
      requestBody:
        description: Tenant to create
        required: True
        content:
          application/json:
            schema:
              x-body-name: tenant
              $ref: "#/components/schemas/Tenant"
      responses:
        "201":
          description: Created tenant
  /tenants/{id}:
    get:
      summary: Returns specified tenant.
      operationId: tenants.show
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Returned tenant"
    put:
      summary: Updates a tenant.
      operationId: tenants.update
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: tenant
              $ref: "#/components/schemas/Tenant"
      responses:
        "200":
          description: Updated tenant
        "404":
          description: Tenant not found
        "406":
          description: Missing field
    delete:
      summary: Deletes a tenant.
      operationId: tenants.delete
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: Deleted tenant
        "404":
          description: Tenant not found
